package javaInroduction.exception;

import java.util.Scanner;

public class ExceptionGenerate {

	public static void main(String[] args) {
		
		Scanner sc=new Scanner(System.in);
		
		/*System.out.println("Enter no1:");
		int no1=sc.nextInt();
		
		System.out.println("Enter no2:");  //0
		int no2=sc.nextInt();
		
		int ans=no1/no2;       //java.lang.ArithmeticException
		
		System.out.println("Answer=" + ans);*/
		

		
		/*String name=null;
		
		System.out.println("name.length()--" + name.length());*/
		
		
		
//		String name="abhi";
//		System.out.println(name.charAt(5));
		
		
		
//		int a[]=new int[5];
//		a[5]=10;
		
		
		
//		String value="123";
//		int no=200;
//		System.out.println(no+value);
		

//		String value="123";
//		int no=Integer.parseInt(value);
//		no=no+200;
//		System.out.println(no);
		
		String value="1f2g3h";
		int no=Integer.parseInt(value);
		no=no+200;
		System.out.println(no);
	}

}
